/*
 * JDateTimeChooser.java
 *
 * Created on 5 październik 2008, 08:44
 */

package wdp.beans;

import java.util.Date;
import javax.swing.JPopupMenu;

/**
 *
 * @author  robson
 */
public class JDateTimeChooser extends javax.swing.JPanel {

    /** Creates new form JDateTimeChooser */
    public JDateTimeChooser() {
        initComponents();
    }

    public Date getDate() {
        return selectedDate;
    }

    public void setDate(Date finish) {
        this.selectedDate = finish;
        jTextFieldDateEditor.setDate(finish);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSelect = new javax.swing.JButton();
        jTextFieldDateEditor = new com.toedter.calendar.JTextFieldDateEditor();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(wdp.WdpApp.class).getContext().getResourceMap(JDateTimeChooser.class);
        jButtonSelect.setText(resourceMap.getString("jButtonSelect.text")); // NOI18N
        jButtonSelect.setName("jButtonSelect"); // NOI18N
        jButtonSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectActionPerformed(evt);
            }
        });

        jTextFieldDateEditor.setText(resourceMap.getString("jTextFieldDateEditor.text")); // NOI18N
        jTextFieldDateEditor.setName("jTextFieldDateEditor"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTextFieldDateEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSelect))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonSelect)
                .addComponent(jTextFieldDateEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jButtonSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectActionPerformed
    popup = new JPopupMenu();
    popup.setLightWeightPopupEnabled(true);
    dateTimePanel = new JDateTimePanel(selectedDate);
    popup.add(dateTimePanel);
    int x = jButtonSelect.getWidth() - (int) popup.getPreferredSize().getWidth();
    int y = jButtonSelect.getY() + jButtonSelect.getHeight();
    popup.show(jButtonSelect, x, y);
    
}//GEN-LAST:event_jButtonSelectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSelect;
    private com.toedter.calendar.JTextFieldDateEditor jTextFieldDateEditor;
    // End of variables declaration//GEN-END:variables
    private JPopupMenu popup = null;
    private JDateTimePanel dateTimePanel = null;
    private Date selectedDate = new Date();
    
}
