/*
 * JDateTimeChooser.java
 *
 * Created on 5 październik 2008, 08:35
 */

package wdp.beans;

import java.util.Date;

/**
 *
 * @author  robson
 */
public class JDateTimePanel extends javax.swing.JPanel {

    /** Creates new form JDateTimeChooser */
    public JDateTimePanel() {
        initComponents();
    }

    public JDateTimePanel(Date selectedDate) {
        initComponents();
        jCalendar1.setDate(selectedDate);
        jTimeChooser1.setDate(selectedDate);
    }
    
    public void setDate(Date selectedDate) {
        jCalendar1.setDate(selectedDate);
        jTimeChooser1.setDate(selectedDate);
    }
    
    public Date getDate() {
        Date retVal = jCalendar1.getDate();
        retVal.setHours(jTimeChooser1.getHour());
        retVal.setMinutes(jTimeChooser1.getMinute());
        return retVal;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jTimeChooser1 = new wdp.beans.JTimeChooser();

        setName("Form"); // NOI18N

        jCalendar1.setName("jCalendar1"); // NOI18N

        jTimeChooser1.setName("jTimeChooser1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(jTimeChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTimeChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar jCalendar1;
    private wdp.beans.JTimeChooser jTimeChooser1;
    // End of variables declaration//GEN-END:variables
}
